name: ${project.artifactId}
version: ${project.version}
authors: [oshcon]
softdepend: [Votifier, Vault, Essentials, SuperVanish, PremiumVanish, ProjectKorra, Towny, TownyChat, MarriageMaster, mcMMO]
website: http://doodcraft.net/
main: net.doodcraft.oshcon.bukkit.doodcore.DoodCorePlugin

commands:
  core:
    description: Administrative command
  discord:
    description: Manage your Discord information
  afk:
    description: Toggle your AFK status
  nick:
    description: Set your nickname
  testtext:
    description: Administrative command
  sudo:
    description: Administrative command
  me:
    description: Express an emote
  say:
    description: Administrative command
  mytime:
    description: Check your total play time
  wild:
    description: Random teleport into unclaimed wilderness
  spawn:
    description: Teleport to the worlds spawn
  seen:
    description: Check a players last join and quit time
  givepet:
    description: Give another player a pet
  home:
    description: Teleport yourself to your home
  homes:
    description: List your homes
  removehome:
    description: Remove a home
  sethome:
    description: Set your home location
  back:
    description: Teleport to your last death location
  vote:
    description: Vote for the server
  tpa:
    description: Send a request to tp to someone
  tpahere:
    description: Send a request for someone to tp to you
  tpcancel:
    description: Cancel your last tp request
  tpaccept:
    description: Accept someones tp request
  tpdeny:
    description: Deny someones tp request

permissions:
  core.command.core:
    description: Allows players to use /core
    default: OP
  core.command.purge:
    description: Allows players to use /core purge
    default: OP
  core.command.reload:
    description: Allows players to use /core reload
    default: OP
  core.command.togglediscord:
    description: Allows players to use /core togglediscord
    default: OP
  core.command.nick:
    description: Allows players to use /nick
    default: OP
  core.command.nick.colors:
    description: Allows players to use color codes in their nicks
    default: OP
  core.command.say:
    description: Allows players to use /say
    default: OP
  core.command.sudo:
    description: Allows players to use /sudo
    default: OP
  core.command.testtext:
    description: Allows players to use /testtext
    default: OP
  core.command.wild:
    description: Allows players to use /wild
    default: OP
  core.command.spawn:
    description: Allows players to use /spawn
    default: OP
  core.command.givepet:
    description: Allows players to use /givepet
    default: OP
  core.command.home:
    description: Allows players to use /home
    default: OP
  core.command.homes:
    description: Allows players to use /homes
    default: OP
  core.command.removehome:
    description: Allows players to use /removehome
    default: OP
  core.command.sethome:
    description: Allows players to use /sethome
    default: OP
  core.chat.colors:
    description: Allows players to use color codes in chat
    default: OP
  core.bypass.afkkick:
    description: Prevents afk players from being kicked
    default: OP
  core.command.back:
    description: Allows players to use /back
    default: OP
  core.bypass.cooldowns:
    description: Allows players to bypass command cooldowns
    default: OP
  core.bypass.vote:
    description: Allows players to bypass vote requirements
    default: OP
  core.command.tps:
    description: Check the current tick rate
    default: OP
  core.bypass.warmups:
    description: Allows players to bypass teleport warmups
    default: OP
  core.command.uuid:
    description: Get a players name based UUID
    default: OP
  core.command.vote:
    decsription: See your vote stats and vote sites
    default: OP
  core.command.tpa:
    description: Allows players to use /tpa
    default: OP
  core.command.tpahere:
    description: Allows players to use /tpahere
    default: OP
  core.command.tpcancel:
    description: Allows players to use /tpcancel
    default: OP
  core.command.tpaccept:
    description: Allows players to use /tpaccept
    default: OP
  core.command.tpdeny:
    description: Allows players to use /tpdeny
    default: OP
  core.command.mytime.others:
    description: View other players mytime report
    default: OP
  core.command.vote.others:
    description: View other players vote report
    default: OP